"""
setup.py — py2app build configuration for Seating Chart Manager.

Usage (from the project root, with this file alongside main.py):

    python3 setup.py py2app

Produces dist/SeatingChartManager.app.

Prerequisites:
    pip install py2app

Icon:
    Run packaging/make_icns.sh first to generate packaging/AppIcon.icns
    from packaging/icon.svg.
"""

from setuptools import setup

APP = ["main.py"]

# Non-Python files that need to ship inside the bundle.
# In our case, all assets are generated at runtime — there's nothing to
# copy. Leaving this as an empty list is correct and documents the fact.
DATA_FILES = []

# Python packages that py2app might not detect automatically. py2app
# walks imports from main.py and generally catches everything, but
# pulp's solvers and reportlab's dynamic registration can sometimes
# slip through — list them explicitly to be safe. Local modules that
# are imported lazily inside methods (rather than at module top) can
# also be missed, so we list ours explicitly.
INCLUDES = [
    "pulp",
    "pulp.apis",
    "reportlab",
    "reportlab.pdfgen",
    "reportlab.lib",
    "reportlab.platypus",
    # Local modules (imported lazily inside methods in some cases)
    "backup",
    "db",
    "theme",
    "exporter",
    "room_canvas",
    "optimizer",
    "optimizer_table_mode",
]

# Packages py2app would include but shouldn't — none in our case.
EXCLUDES = []

OPTIONS = {
    # Icon: the .icns generated by make_icns.sh
    "iconfile": "packaging/AppIcon.icns",

    # Build argv_emulation=False on modern Python/macOS — it uses an
    # older carbon API that's been removed. We don't need file-open
    # events from Finder anyway.
    "argv_emulation": False,

    # The app's Info.plist. CFBundleName controls what appears in the
    # Dock and menu bar; the filename of the .app itself is determined
    # by name= in setup() below (we post-rename it in build_app.sh for
    # clean output).
    "plist": {
        "CFBundleName":            "Seating Chart Manager",
        "CFBundleDisplayName":     "Seating Chart Manager",
        "CFBundleIdentifier":      "com.seatingchartmanager.app",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion":         "1.0.0",
        # LSMinimumSystemVersion: the lowest macOS that can run the
        # bundled Python. 11.0 (Big Sur) is a safe floor for Apple
        # Silicon-only builds; older macOS predates the M1 anyway.
        "LSMinimumSystemVersion":  "11.0",
        # NSHighResolutionCapable enables Retina rendering — without
        # this, the app runs in 2x-upscaled low-res mode on Retina
        # Macs and looks awful.
        "NSHighResolutionCapable": True,
        # Human-readable copyright shown in About dialogs.
        "NSHumanReadableCopyright": "© 2026 Seating Chart Manager",
    },

    "includes": INCLUDES,
    "excludes": EXCLUDES,

    # "alias" builds are symlink-based dev builds that rebuild instantly
    # but only work on the machine where they're built. We want a real,
    # distributable standalone bundle, so: no alias.
    "alias": False,

    # Strip debug symbols and compress where possible — smaller bundle.
    "optimize": 2,
}

setup(
    name="SeatingChartManager",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)